--
-- PostgreSQL database dump
--

\restrict 6ODai5UfsM9K8FKwPlPWUVvU232b8pX73S7aWqYlQ6bMplWqasLr8vPd8pC7YWX

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: academics_department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.academics_department (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(20) NOT NULL
);


ALTER TABLE public.academics_department OWNER TO postgres;

--
-- Name: academics_department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.academics_department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academics_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_hodprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_hodprofile (
    id bigint NOT NULL,
    phone_no character varying(11) NOT NULL,
    profile_pic character varying(100),
    department_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.accounts_hodprofile OWNER TO postgres;

--
-- Name: accounts_hodprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_hodprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_hodprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_studentprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_studentprofile (
    id bigint NOT NULL,
    registration_no character varying(30) NOT NULL,
    phone_no character varying(11) NOT NULL,
    address character varying(200) NOT NULL,
    date_of_birth date,
    semester integer,
    degree_program character varying(100) NOT NULL,
    campus character varying(100) NOT NULL,
    profile_pic character varying(100),
    department_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT accounts_studentprofile_semester_check CHECK ((semester >= 0))
);


ALTER TABLE public.accounts_studentprofile OWNER TO postgres;

--
-- Name: accounts_studentprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_studentprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_studentprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_teacherprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_teacherprofile (
    id bigint NOT NULL,
    employee_id character varying(30) NOT NULL,
    phone_no character varying(11) NOT NULL,
    address character varying(200) NOT NULL,
    designation character varying(100) NOT NULL,
    cnic character varying(15),
    profile_pic character varying(100),
    department_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.accounts_teacherprofile OWNER TO postgres;

--
-- Name: accounts_teacherprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_teacherprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_teacherprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessments_marks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assessments_marks (
    id bigint NOT NULL,
    sessional numeric(5,2) NOT NULL,
    midterm numeric(5,2) NOT NULL,
    final numeric(5,2) NOT NULL,
    enrollment_id bigint NOT NULL
);


ALTER TABLE public.assessments_marks OWNER TO postgres;

--
-- Name: assessments_marks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assessments_marks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessments_marks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_attendance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance_attendance (
    id bigint NOT NULL,
    date date NOT NULL,
    present boolean NOT NULL,
    enrollment_id bigint NOT NULL
);


ALTER TABLE public.attendance_attendance OWNER TO postgres;

--
-- Name: attendance_attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attendance_attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_course (
    id bigint NOT NULL,
    semester integer NOT NULL,
    name character varying(150) NOT NULL,
    code character varying(30) NOT NULL,
    credit_hours integer NOT NULL,
    description text NOT NULL,
    department_id bigint NOT NULL,
    CONSTRAINT courses_course_credit_hours_check CHECK ((credit_hours >= 0)),
    CONSTRAINT courses_course_semester_check CHECK ((semester >= 0))
);


ALTER TABLE public.courses_course OWNER TO postgres;

--
-- Name: courses_course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_courseoffering; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_courseoffering (
    id bigint NOT NULL,
    academic_year character varying(20) NOT NULL,
    course_id bigint NOT NULL,
    teacher_id bigint NOT NULL
);


ALTER TABLE public.courses_courseoffering OWNER TO postgres;

--
-- Name: courses_courseoffering_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_courseoffering ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_courseoffering_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: enrollments_enrollment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enrollments_enrollment (
    id bigint NOT NULL,
    enrolled_at timestamp with time zone NOT NULL,
    course_offering_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.enrollments_enrollment OWNER TO postgres;

--
-- Name: enrollments_enrollment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.enrollments_enrollment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollments_enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lms_assignments_assignment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lms_assignments_assignment (
    id bigint NOT NULL,
    title character varying(150) NOT NULL,
    description text NOT NULL,
    due_date timestamp with time zone NOT NULL,
    assignment_file character varying(100),
    created_at timestamp with time zone NOT NULL,
    course_offering_id bigint NOT NULL
);


ALTER TABLE public.lms_assignments_assignment OWNER TO postgres;

--
-- Name: lms_assignments_assignment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lms_assignments_assignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lms_assignments_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lms_assignments_submission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lms_assignments_submission (
    id bigint NOT NULL,
    submission_file character varying(100),
    submitted_at timestamp with time zone NOT NULL,
    assignment_id bigint NOT NULL,
    enrollment_id bigint NOT NULL
);


ALTER TABLE public.lms_assignments_submission OWNER TO postgres;

--
-- Name: lms_assignments_submission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lms_assignments_submission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lms_assignments_submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: academics_department; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.academics_department (id, name, code) FROM stdin;
1	Computer Science	CS
\.


--
-- Data for Name: accounts_hodprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_hodprofile (id, phone_no, profile_pic, department_id, user_id) FROM stdin;
1			1	4
\.


--
-- Data for Name: accounts_studentprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_studentprofile (id, registration_no, phone_no, address, date_of_birth, semester, degree_program, campus, profile_pic, department_id, user_id) FROM stdin;
1	CS-001			\N	1	BS Computer Science			1	3
\.


--
-- Data for Name: accounts_teacherprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_teacherprofile (id, employee_id, phone_no, address, designation, cnic, profile_pic, department_id, user_id) FROM stdin;
1	T-001			Lecturer	\N		1	2
\.


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role) FROM stdin;
1	pbkdf2_sha256$1500000$l9cfxGUy2x68JFwgJUT0kl$8DNJKP5yZaUP18X3S0LdkQwJj4L3f10ZhdSof2cj7hs=	2026-08-31 09:17:22.624+05	t	danish				t	t	2026-08-31 09:16:45.424+05	student
2	pbkdf2_sha256$1500000$qqSqVj4XKdPQkUDQ897jLG$lr8q6mnnJ4ZylPrMif0LWbOEQ1Y62ecS7a7tvNXGWtU=	2026-09-01 10:23:49.699+05	f	eid				f	t	2026-08-31 09:22:05.832+05	teacher
3	pbkdf2_sha256$1500000$IYD4tpU9xjpm8D92vU20kp$sAQMMnP31W5EA1tC+jn0OTmqQYydlA/2b1xN36SgD4U=	2026-09-01 10:24:21.735+05	f	danishkhan				f	t	2026-08-31 09:23:16.906+05	student
4	pbkdf2_sha256$1500000$h5mZzrSch280BYuGLGQaju$o04//PA2rZPvA+2aistyHV4hXGdSSWZOCSsJAjXpXu0=	2026-09-01 10:21:07.33+05	f	hod				f	t	2026-08-31 09:48:32.349+05	hod
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: assessments_marks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assessments_marks (id, sessional, midterm, final, enrollment_id) FROM stdin;
\.


--
-- Data for Name: attendance_attendance; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attendance_attendance (id, date, present, enrollment_id) FROM stdin;
1	2026-08-31	t	1
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	9	add_user
22	Can change user	9	change_user
23	Can delete user	9	delete_user
24	Can view user	9	view_user
25	Can add hod profile	6	add_hodprofile
26	Can change hod profile	6	change_hodprofile
27	Can delete hod profile	6	delete_hodprofile
28	Can view hod profile	6	view_hodprofile
29	Can add student profile	7	add_studentprofile
30	Can change student profile	7	change_studentprofile
31	Can delete student profile	7	delete_studentprofile
32	Can view student profile	7	view_studentprofile
33	Can add teacher profile	8	add_teacherprofile
34	Can change teacher profile	8	change_teacherprofile
35	Can delete teacher profile	8	delete_teacherprofile
36	Can view teacher profile	8	view_teacherprofile
37	Can add department	10	add_department
38	Can change department	10	change_department
39	Can delete department	10	delete_department
40	Can view department	10	view_department
41	Can add course	11	add_course
42	Can change course	11	change_course
43	Can delete course	11	delete_course
44	Can view course	11	view_course
45	Can add course offering	12	add_courseoffering
46	Can change course offering	12	change_courseoffering
47	Can delete course offering	12	delete_courseoffering
48	Can view course offering	12	view_courseoffering
49	Can add enrollment	13	add_enrollment
50	Can change enrollment	13	change_enrollment
51	Can delete enrollment	13	delete_enrollment
52	Can view enrollment	13	view_enrollment
53	Can add attendance	14	add_attendance
54	Can change attendance	14	change_attendance
55	Can delete attendance	14	delete_attendance
56	Can view attendance	14	view_attendance
57	Can add marks	15	add_marks
58	Can change marks	15	change_marks
59	Can delete marks	15	delete_marks
60	Can view marks	15	view_marks
61	Can add assignment	16	add_assignment
62	Can change assignment	16	change_assignment
63	Can delete assignment	16	delete_assignment
64	Can view assignment	16	view_assignment
65	Can add submission	17	add_submission
66	Can change submission	17	change_submission
67	Can delete submission	17	delete_submission
68	Can view submission	17	view_submission
\.


--
-- Data for Name: courses_course; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_course (id, semester, name, code, credit_hours, description, department_id) FROM stdin;
1	1	Programming Fundamentals	CS-101	3		1
2	1	Programming Fundamentals	PF	3	Introduction to programming	1
\.


--
-- Data for Name: courses_courseoffering; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_courseoffering (id, academic_year, course_id, teacher_id) FROM stdin;
1	2026	1	1
2	2026-27	2	1
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-08-31 09:21:33.174+05	1	Computer Science (CS)	1	[{"added": {}}]	10	1
2	2026-08-31 09:22:07.096+05	2	eid (teacher)	1	[{"added": {}}]	9	1
3	2026-08-31 09:22:38.417+05	1	eid - Teacher	1	[{"added": {}}]	8	1
4	2026-08-31 09:23:18.241+05	3	danishkhan (student)	1	[{"added": {}}]	9	1
5	2026-08-31 09:23:54.633+05	1	danishkhan - Student	1	[{"added": {}}]	7	1
6	2026-08-31 09:26:24.204+05	1	CS-101 - Programming Fundamentals	1	[{"added": {}}]	11	1
7	2026-08-31 09:26:47.662+05	1	CS-101 - eid (2026)	1	[{"added": {}}]	12	1
8	2026-08-31 09:48:33.592+05	4	hod (hod)	1	[{"added": {}}]	9	1
9	2026-08-31 09:50:29.254+05	1	danishkhan - Student	2	[{"changed": {"fields": ["Registration no", "Semester", "Degree program"]}}]	7	1
10	2026-08-31 09:50:54.666+05	1	eid - Teacher	2	[{"changed": {"fields": ["Employee id", "Designation"]}}]	8	1
11	2026-08-31 09:51:14.512+05	1	hod - HOD	1	[{"added": {}}]	6	1
12	2026-08-31 09:52:19.229+05	2	PF - Programming Fundamentals	1	[{"added": {}}]	11	1
13	2026-08-31 09:52:45.486+05	2	PF - eid (2026-27)	1	[{"added": {}}]	12	1
14	2026-08-31 09:53:11.553+05	1	danishkhan - PF - 2026-27	1	[{"added": {}}]	13	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	hodprofile
7	accounts	studentprofile
8	accounts	teacherprofile
9	accounts	user
10	academics	department
11	courses	course
12	courses	courseoffering
13	enrollments	enrollment
14	attendance	attendance
15	assessments	marks
16	lms_assignments	assignment
17	lms_assignments	submission
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	academics	0001_initial	2026-09-02 09:53:04.473509+05
2	contenttypes	0001_initial	2026-09-02 09:53:04.491123+05
3	contenttypes	0002_remove_content_type_name	2026-09-02 09:53:04.502158+05
4	auth	0001_initial	2026-09-02 09:53:04.567264+05
5	auth	0002_alter_permission_name_max_length	2026-09-02 09:53:04.574974+05
6	auth	0003_alter_user_email_max_length	2026-09-02 09:53:04.580482+05
7	auth	0004_alter_user_username_opts	2026-09-02 09:53:04.585994+05
8	auth	0005_alter_user_last_login_null	2026-09-02 09:53:04.593268+05
9	auth	0006_require_contenttypes_0002	2026-09-02 09:53:04.595256+05
10	auth	0007_alter_validators_add_error_messages	2026-09-02 09:53:04.601502+05
11	auth	0008_alter_user_username_max_length	2026-09-02 09:53:04.607577+05
12	auth	0009_alter_user_last_name_max_length	2026-09-02 09:53:04.614506+05
13	auth	0010_alter_group_name_max_length	2026-09-02 09:53:04.623211+05
14	auth	0011_update_proxy_permissions	2026-09-02 09:53:04.629848+05
15	auth	0012_alter_user_first_name_max_length	2026-09-02 09:53:04.637047+05
16	accounts	0001_initial	2026-09-02 09:53:04.773668+05
17	admin	0001_initial	2026-09-02 09:53:04.800802+05
18	admin	0002_logentry_remove_auto_add	2026-09-02 09:53:04.809462+05
19	admin	0003_logentry_add_action_flag_choices	2026-09-02 09:53:04.818076+05
20	courses	0001_initial	2026-09-02 09:53:04.88492+05
21	enrollments	0001_initial	2026-09-02 09:53:04.918989+05
22	assessments	0001_initial	2026-09-02 09:53:04.951195+05
23	attendance	0001_initial	2026-09-02 09:53:04.981651+05
24	lms_assignments	0001_initial	2026-09-02 09:53:05.045667+05
25	sessions	0001_initial	2026-09-02 09:53:05.057478+05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
6xcz9hmslnv981a3zct0p0zspold00jp	.eJxVjDsOwjAQBe_iGln-bLIxJX3OYNneNQ4gR4qTCnF3EikFtDPz3lv4sK3Fb40XP5G4CiMuvyyG9OR6CHqEep9lmuu6TFEeiTxtk-NM_Lqd7d9BCa3sa-xAY2ZDfUiEQFFZtB05pUD1A1oLzjo2KeYdEDgzZNaEDBy0RQXi8wXIjjcT:1x0uL8:G95YeGLg-kAT5S9r2L_hBqurT_Dga3CNuhg04zrYXYA	2026-09-14 10:13:50.216+05
9h1iivq5xv8t4wkx9ket2dz25eiwefxl	.eJxVjEEOwiAQRe_C2hDagUJcuvcMZIYZpGogKe3KeHdt0oVu_3vvv1TEbS1x67LEmdVZgTr9boTpIXUHfMd6azq1ui4z6V3RB-362liel8P9OyjYy7emQchTnnzKHnPKNBoIzgnagMzBsw3gjHHokwGBkM00AmXDHpJYN6j3Bw1qOFw:1x1Gyr:DbySvExXl9nIbQyg3LZXQukOKcSDpyGtaotnwPxBW4c	2026-09-15 10:24:21.75+05
\.


--
-- Data for Name: enrollments_enrollment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.enrollments_enrollment (id, enrolled_at, course_offering_id, student_id) FROM stdin;
1	2026-08-31 09:53:11.547+05	2	1
\.


--
-- Data for Name: lms_assignments_assignment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lms_assignments_assignment (id, title, description, due_date, assignment_file, created_at, course_offering_id) FROM stdin;
1	Programming Assignment 1	Write a simple Python program.	2026-09-01 14:55:00+05		2026-08-31 09:55:57.893+05	2
\.


--
-- Data for Name: lms_assignments_submission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lms_assignments_submission (id, submission_file, submitted_at, assignment_id, enrollment_id) FROM stdin;
1	assignments/student/Workflow_Audit_Danish_1.docx	2026-08-31 09:56:48.63+05	1	1
\.


--
-- Name: academics_department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.academics_department_id_seq', 1, true);


--
-- Name: accounts_hodprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_hodprofile_id_seq', 1, true);


--
-- Name: accounts_studentprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_studentprofile_id_seq', 1, true);


--
-- Name: accounts_teacherprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_teacherprofile_id_seq', 1, true);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 4, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: assessments_marks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assessments_marks_id_seq', 1, false);


--
-- Name: attendance_attendance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attendance_attendance_id_seq', 1, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: courses_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_course_id_seq', 2, true);


--
-- Name: courses_courseoffering_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_courseoffering_id_seq', 2, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 14, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: enrollments_enrollment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.enrollments_enrollment_id_seq', 1, true);


--
-- Name: lms_assignments_assignment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lms_assignments_assignment_id_seq', 1, true);


--
-- Name: lms_assignments_submission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lms_assignments_submission_id_seq', 1, true);


--
-- Name: academics_department academics_department_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.academics_department
    ADD CONSTRAINT academics_department_code_key UNIQUE (code);


--
-- Name: academics_department academics_department_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.academics_department
    ADD CONSTRAINT academics_department_name_key UNIQUE (name);


--
-- Name: academics_department academics_department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.academics_department
    ADD CONSTRAINT academics_department_pkey PRIMARY KEY (id);


--
-- Name: accounts_hodprofile accounts_hodprofile_department_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_hodprofile
    ADD CONSTRAINT accounts_hodprofile_department_id_key UNIQUE (department_id);


--
-- Name: accounts_hodprofile accounts_hodprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_hodprofile
    ADD CONSTRAINT accounts_hodprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_hodprofile accounts_hodprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_hodprofile
    ADD CONSTRAINT accounts_hodprofile_user_id_key UNIQUE (user_id);


--
-- Name: accounts_studentprofile accounts_studentprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_studentprofile
    ADD CONSTRAINT accounts_studentprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_studentprofile accounts_studentprofile_registration_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_studentprofile
    ADD CONSTRAINT accounts_studentprofile_registration_no_key UNIQUE (registration_no);


--
-- Name: accounts_studentprofile accounts_studentprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_studentprofile
    ADD CONSTRAINT accounts_studentprofile_user_id_key UNIQUE (user_id);


--
-- Name: accounts_teacherprofile accounts_teacherprofile_cnic_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_teacherprofile
    ADD CONSTRAINT accounts_teacherprofile_cnic_key UNIQUE (cnic);


--
-- Name: accounts_teacherprofile accounts_teacherprofile_employee_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_teacherprofile
    ADD CONSTRAINT accounts_teacherprofile_employee_id_key UNIQUE (employee_id);


--
-- Name: accounts_teacherprofile accounts_teacherprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_teacherprofile
    ADD CONSTRAINT accounts_teacherprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_teacherprofile accounts_teacherprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_teacherprofile
    ADD CONSTRAINT accounts_teacherprofile_user_id_key UNIQUE (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: assessments_marks assessments_marks_enrollment_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessments_marks
    ADD CONSTRAINT assessments_marks_enrollment_id_key UNIQUE (enrollment_id);


--
-- Name: assessments_marks assessments_marks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessments_marks
    ADD CONSTRAINT assessments_marks_pkey PRIMARY KEY (id);


--
-- Name: attendance_attendance attendance_attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance_attendance
    ADD CONSTRAINT attendance_attendance_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: courses_course courses_course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_course
    ADD CONSTRAINT courses_course_pkey PRIMARY KEY (id);


--
-- Name: courses_courseoffering courses_courseoffering_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_courseoffering
    ADD CONSTRAINT courses_courseoffering_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: enrollments_enrollment enrollments_enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollments_enrollment
    ADD CONSTRAINT enrollments_enrollment_pkey PRIMARY KEY (id);


--
-- Name: lms_assignments_assignment lms_assignments_assignment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lms_assignments_assignment
    ADD CONSTRAINT lms_assignments_assignment_pkey PRIMARY KEY (id);


--
-- Name: lms_assignments_submission lms_assignments_submission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lms_assignments_submission
    ADD CONSTRAINT lms_assignments_submission_pkey PRIMARY KEY (id);


--
-- Name: lms_assignments_submission unique_assignment_submission; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lms_assignments_submission
    ADD CONSTRAINT unique_assignment_submission UNIQUE (assignment_id, enrollment_id);


--
-- Name: attendance_attendance unique_attendance_per_day; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance_attendance
    ADD CONSTRAINT unique_attendance_per_day UNIQUE (enrollment_id, date);


--
-- Name: courses_courseoffering unique_course_offering; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_courseoffering
    ADD CONSTRAINT unique_course_offering UNIQUE (course_id, teacher_id, academic_year);


--
-- Name: courses_course unique_course_per_department_semester; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_course
    ADD CONSTRAINT unique_course_per_department_semester UNIQUE (department_id, semester, code);


--
-- Name: enrollments_enrollment unique_student_course_offering; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollments_enrollment
    ADD CONSTRAINT unique_student_course_offering UNIQUE (student_id, course_offering_id);


--
-- Name: academics_department_code_e68a2c68_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX academics_department_code_e68a2c68_like ON public.academics_department USING btree (code varchar_pattern_ops);


--
-- Name: academics_department_name_2e89c541_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX academics_department_name_2e89c541_like ON public.academics_department USING btree (name varchar_pattern_ops);


--
-- Name: accounts_studentprofile_department_id_340eacd0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_studentprofile_department_id_340eacd0 ON public.accounts_studentprofile USING btree (department_id);


--
-- Name: accounts_studentprofile_registration_no_2e151075_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_studentprofile_registration_no_2e151075_like ON public.accounts_studentprofile USING btree (registration_no varchar_pattern_ops);


--
-- Name: accounts_teacherprofile_cnic_6d1f847a_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_teacherprofile_cnic_6d1f847a_like ON public.accounts_teacherprofile USING btree (cnic varchar_pattern_ops);


--
-- Name: accounts_teacherprofile_department_id_a794002c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_teacherprofile_department_id_a794002c ON public.accounts_teacherprofile USING btree (department_id);


--
-- Name: accounts_teacherprofile_employee_id_61029a8a_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_teacherprofile_employee_id_61029a8a_like ON public.accounts_teacherprofile USING btree (employee_id varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: attendance_attendance_enrollment_id_7a498eb1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX attendance_attendance_enrollment_id_7a498eb1 ON public.attendance_attendance USING btree (enrollment_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: courses_course_department_id_efdfb636; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_course_department_id_efdfb636 ON public.courses_course USING btree (department_id);


--
-- Name: courses_courseoffering_course_id_e8fae9f7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_courseoffering_course_id_e8fae9f7 ON public.courses_courseoffering USING btree (course_id);


--
-- Name: courses_courseoffering_teacher_id_a79fd0f1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_courseoffering_teacher_id_a79fd0f1 ON public.courses_courseoffering USING btree (teacher_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: enrollments_enrollment_course_offering_id_2dd4a9bd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX enrollments_enrollment_course_offering_id_2dd4a9bd ON public.enrollments_enrollment USING btree (course_offering_id);


--
-- Name: enrollments_enrollment_student_id_92696b89; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX enrollments_enrollment_student_id_92696b89 ON public.enrollments_enrollment USING btree (student_id);


--
-- Name: lms_assignments_assignment_course_offering_id_726c4c4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX lms_assignments_assignment_course_offering_id_726c4c4b ON public.lms_assignments_assignment USING btree (course_offering_id);


--
-- Name: lms_assignments_submission_assignment_id_42beffaa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX lms_assignments_submission_assignment_id_42beffaa ON public.lms_assignments_submission USING btree (assignment_id);


--
-- Name: lms_assignments_submission_enrollment_id_c55e509d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX lms_assignments_submission_enrollment_id_c55e509d ON public.lms_assignments_submission USING btree (enrollment_id);


--
-- Name: accounts_hodprofile accounts_hodprofile_department_id_c4819e53_fk_academics; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_hodprofile
    ADD CONSTRAINT accounts_hodprofile_department_id_c4819e53_fk_academics FOREIGN KEY (department_id) REFERENCES public.academics_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_hodprofile accounts_hodprofile_user_id_2bf394fc_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_hodprofile
    ADD CONSTRAINT accounts_hodprofile_user_id_2bf394fc_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_studentprofile accounts_studentprof_department_id_340eacd0_fk_academics; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_studentprofile
    ADD CONSTRAINT accounts_studentprof_department_id_340eacd0_fk_academics FOREIGN KEY (department_id) REFERENCES public.academics_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_studentprofile accounts_studentprofile_user_id_04a48d2e_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_studentprofile
    ADD CONSTRAINT accounts_studentprofile_user_id_04a48d2e_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_teacherprofile accounts_teacherprof_department_id_a794002c_fk_academics; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_teacherprofile
    ADD CONSTRAINT accounts_teacherprof_department_id_a794002c_fk_academics FOREIGN KEY (department_id) REFERENCES public.academics_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_teacherprofile accounts_teacherprofile_user_id_9582b3e8_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_teacherprofile
    ADD CONSTRAINT accounts_teacherprofile_user_id_9582b3e8_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: assessments_marks assessments_marks_enrollment_id_4c37ed2e_fk_enrollmen; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessments_marks
    ADD CONSTRAINT assessments_marks_enrollment_id_4c37ed2e_fk_enrollmen FOREIGN KEY (enrollment_id) REFERENCES public.enrollments_enrollment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attendance_attendance attendance_attendanc_enrollment_id_7a498eb1_fk_enrollmen; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance_attendance
    ADD CONSTRAINT attendance_attendanc_enrollment_id_7a498eb1_fk_enrollmen FOREIGN KEY (enrollment_id) REFERENCES public.enrollments_enrollment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_course courses_course_department_id_efdfb636_fk_academics; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_course
    ADD CONSTRAINT courses_course_department_id_efdfb636_fk_academics FOREIGN KEY (department_id) REFERENCES public.academics_department(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_courseoffering courses_courseofferi_teacher_id_a79fd0f1_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_courseoffering
    ADD CONSTRAINT courses_courseofferi_teacher_id_a79fd0f1_fk_accounts_ FOREIGN KEY (teacher_id) REFERENCES public.accounts_teacherprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_courseoffering courses_courseoffering_course_id_e8fae9f7_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_courseoffering
    ADD CONSTRAINT courses_courseoffering_course_id_e8fae9f7_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: enrollments_enrollment enrollments_enrollme_course_offering_id_2dd4a9bd_fk_courses_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollments_enrollment
    ADD CONSTRAINT enrollments_enrollme_course_offering_id_2dd4a9bd_fk_courses_c FOREIGN KEY (course_offering_id) REFERENCES public.courses_courseoffering(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: enrollments_enrollment enrollments_enrollme_student_id_92696b89_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollments_enrollment
    ADD CONSTRAINT enrollments_enrollme_student_id_92696b89_fk_accounts_ FOREIGN KEY (student_id) REFERENCES public.accounts_studentprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lms_assignments_assignment lms_assignments_assi_course_offering_id_726c4c4b_fk_courses_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lms_assignments_assignment
    ADD CONSTRAINT lms_assignments_assi_course_offering_id_726c4c4b_fk_courses_c FOREIGN KEY (course_offering_id) REFERENCES public.courses_courseoffering(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lms_assignments_submission lms_assignments_subm_assignment_id_42beffaa_fk_lms_assig; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lms_assignments_submission
    ADD CONSTRAINT lms_assignments_subm_assignment_id_42beffaa_fk_lms_assig FOREIGN KEY (assignment_id) REFERENCES public.lms_assignments_assignment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lms_assignments_submission lms_assignments_subm_enrollment_id_c55e509d_fk_enrollmen; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lms_assignments_submission
    ADD CONSTRAINT lms_assignments_subm_enrollment_id_c55e509d_fk_enrollmen FOREIGN KEY (enrollment_id) REFERENCES public.enrollments_enrollment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 6ODai5UfsM9K8FKwPlPWUVvU232b8pX73S7aWqYlQ6bMplWqasLr8vPd8pC7YWX

