# Generated by Django 6.1 on 2026-08-31 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('credit_hours', models.PositiveIntegerField(default=3)),
                ('description', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.department')),
            ],
            options={
                'ordering': ['semester', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='accounts.teacherprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('department', 'semester', 'code'), name='unique_course_per_department_semester'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('course', 'teacher', 'academic_year'), name='unique_course_offering'),
        ),
    ]
