# Generated by Django 6.1 on 2026-08-31 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessional', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('midterm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='enrollments.enrollment')),
            ],
            options={
                'ordering': ['enrollment'],
            },
        ),
    ]
